//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGestionHotel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class administrateur
    {
        public int id_admin { get; set; }
        [Required(ErrorMessage = "Last name is required.")]
        public string nom_admin { get; set; }
        [Required(ErrorMessage = "First name is required.")]
        public string prenom_admin { get; set; }
        [Required(ErrorMessage = "Email name is required.")]
        [EmailAddress]
        public string email_admin { get; set; }
        [Required(ErrorMessage = "Mobile phone number is required.")]
        [Phone]
        public string tel_admin { get; set; }
        [Required(ErrorMessage = "Login is required.")]
        public string login_admin { get; set; }
        [Required(ErrorMessage = "Password is required.")]
        public string mdp_admin { get; set; }
        public bool is_superadmin { get; set; }
    }
}
